# Site settings
title: NMC
description: Personal Blog
keywords: 
author: Nicotine_Patch
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" 
twitter: "https://twitter.com/nclmefcm"
instagram: "https://www.instagram.com/nclmefc/"
linkedin: "https://www.linkedin.com/in/nicole-mae-chang-823b4416a/"
github: "https://github.com/colekid"
